## Problem

$$f(w_1, w_2) = 0.1w_1^2 + 2w_2^2 \;\;\;\;\;\;\;(1)$$

In [1]:
import numpy as np

### RMSprop

In [2]:
def df_w(w):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    #################### YOUR CODE HERE ####################
    dw1 = 0.2 * w[0]
    dw2 = 4 * w[1]
    dW = np.array([dw1, dw2], dtype=np.float32)
    ########################################################
    return dW

In [4]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật tóan RMSProp để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6
    #################### YOUR CODE HERE ####################

    S = gamma * S + (1 - gamma) * (dW ** 2)
    W = W - lr * (dW / np.sqrt(S + epsilon))

    ########################################################
    return W, S

In [5]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]
    #################### YOUR CODE HERE ####################
    # Tạo vòng lặp theo số lần epochs
    # tìm gradient dW gồm dw1 và dw2
    # dùng thuật toán optimization cập nhật w1, w2, s1, s2
    # append cặp [w1, w2] vào list results
    for i in range(epochs):
        dW = df_w(W)
        W, S = optimizer(W, dW, lr, S, 0.9)
        results.append(W)
    ########################################################
    return results

In [6]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.0513215, -1.0513167], dtype=float32),
 array([-3.4351976, -0.5915234], dtype=float32),
 array([-2.958937 , -0.3294394], dtype=float32),
 array([-2.5654628, -0.1775648], dtype=float32),
 array([-2.2292054 , -0.09163254], dtype=float32),
 array([-1.9362674 , -0.04494498], dtype=float32),
 array([-1.6781768 , -0.02081422], dtype=float32),
 array([-1.4493498 , -0.00903558], dtype=float32),
 array([-1.2458819, -0.0036459], dtype=float32),
 array([-1.0649029 , -0.00135351], dtype=float32),
 array([-9.0420210e-01, -4.5644387e-04], dtype=float32),
 array([-7.6199633e-01, -1.3756269e-04], dtype=float32),
 array([-6.3677835e-01, -3.6260019e-05], dtype=float32),
 array([-5.272151e-01, -8.113349e-06], dtype=float32),
 array([-4.3207839e-01, -1.4747279e-06], dtype=float32),
 array([-3.5019839e-01, -2.0278276e-07], dtype=float32),
 array([-2.8043455e-01, -1.8422952e-08], dtype=float32),
 array([-2.2165975e-01, -7.6773077e-10], dtype=float32),
 array([-1.